name : Lint

on:
  pull_request:
  push:


jobs:
  java-lint:
    name : Lint
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v4

      - uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}



